-- Skema database Personal Tracker (Neon Postgres).
--
-- Referensi, bukan migration terkelola. Tabel dan view dibuat/diubah
-- langsung di Neon SQL editor (lihat CLAUDE.md), bukan lewat berkas ini —
-- menjalankan file ini tidak akan menyinkronkan apa pun secara otomatis.
-- Direkonstruksi 2026-09-12 dari information_schema.columns dan
-- pg_constraint/pg_indexes yang ditanya langsung ke Neon, bukan hasil
-- pg_dump. Kalau ada ALTER TABLE atau CREATE OR REPLACE VIEW yang
-- dijalankan di database sesudah tanggal ini, perbarui berkas ini juga
-- supaya tidak makin menyimpang dari kondisi nyata.

-- ============================================================
-- Modul Keuangan
-- ============================================================

create table wallets (
  id           integer generated by default as identity primary key,
  nama         text not null unique,
  jenis        text not null check (jenis = any (array['Rekening','E-Wallet','Cash','Investasi','Lainnya'])),
  saldo_awal   bigint not null default 0 check (saldo_awal >= -1000000000000 and saldo_awal <= 1000000000000),
  tanggal_awal date not null,
  catatan      text not null default '',
  aktif        boolean not null default true,
  urutan       integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint nama_terisi check (length(trim(nama)) > 0)
);

create table incomes (
  id            bigint generated by default as identity primary key,
  month         text not null,
  year          integer not null,
  tanggal       date not null,
  description   text not null,
  amount        bigint not null check (amount >= 0),
  created_at    timestamptz not null default now(),
  recurring_id  integer,
  recurring_for text,
  wallet_id     integer references wallets(id) on delete set null
);
create index idx_income_period on incomes (year, month);
create index incomes_wallet_idx on incomes (wallet_id) where wallet_id is not null;
create unique index incomes_recurring_uniq on incomes (recurring_id, recurring_for)
  where recurring_id is not null and recurring_for is not null;
-- incomes_recurring_unik: index unik lain dengan predicate sedikit beda
-- (tanpa cek recurring_for is not null). Sisa dari migrasi, dua-duanya
-- hidup barengan sekarang. Aman didiamkan, tidak urgent untuk disatukan.
create unique index incomes_recurring_unik on incomes (recurring_id, recurring_for)
  where recurring_id is not null;

create table variable_expenses (
  id            bigint generated by default as identity primary key,
  month         text not null,
  year          integer not null,
  tanggal       date not null,
  description   text not null,
  category      text not null,
  amount        bigint not null check (amount >= 0),
  created_at    timestamptz not null default now(),
  recurring_id  integer,
  recurring_for text,
  wallet_id     integer references wallets(id) on delete set null,
  transfer_id   integer references wallet_transfers(id) on delete cascade
);
create index idx_var_period on variable_expenses (year, month);
create index variable_wallet_idx on variable_expenses (wallet_id) where wallet_id is not null;
create index variable_transfer_idx on variable_expenses (transfer_id) where transfer_id is not null;
create unique index variable_recurring_unik on variable_expenses (recurring_id, recurring_for)
  where recurring_id is not null;
create unique index varexp_recurring_uniq on variable_expenses (recurring_id, recurring_for)
  where recurring_id is not null and recurring_for is not null;

create table fixed_costs (
  id         bigint generated by default as identity primary key,
  month      text not null,
  year       integer not null,
  item       text not null,
  amount     bigint not null default 0 check (amount >= 0),
  wallet_id  integer references wallets(id) on delete set null,
  unique (month, year, item)
);
create index fixed_wallet_idx on fixed_costs (wallet_id) where wallet_id is not null;

create table saving_goals (
  id         integer generated by default as identity primary key,
  component  text not null unique,
  target     bigint not null check (target > 0 and target <= 100000000000),
  deadline   date,
  catatan    text not null default '',
  aktif      boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint component_terisi check (length(trim(component)) > 0)
);

create table savings (
  id         bigint generated by default as identity primary key,
  month      text not null,
  year       integer not null,
  component  text not null,
  amount     bigint not null check (amount >= 0),
  created_at timestamptz not null default now(),
  wallet_id  integer references wallets(id) on delete set null,
  goal_id    integer references saving_goals(id) on delete set null
);
create index idx_saving_period on savings (year, month);
create index savings_component_idx on savings (component);

create table wallet_transfers (
  id         integer generated by default as identity primary key,
  tanggal    date not null,
  dari_id    integer not null references wallets(id) on delete restrict,
  ke_id      integer not null references wallets(id) on delete restrict,
  amount     bigint not null check (amount > 0 and amount <= 1000000000),
  catatan    text not null default '',
  created_at timestamptz not null default now(),
  fee        bigint not null default 0 check (fee >= 0 and fee <= 1000000),
  constraint beda_dompet check (dari_id <> ke_id)
);
create index transfers_tanggal_idx on wallet_transfers (tanggal desc);

create table recurring (
  id          integer generated by default as identity primary key,
  jenis       text not null check (jenis = any (array['income','variable','fixed'])),
  description text not null default '',
  item        text,
  category    text,
  amount      bigint not null check (amount >= 0 and amount <= 1000000000),
  hari        integer not null default 20 check (hari >= 1 and hari <= 31),
  aktif       boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  wallet_id   integer references wallets(id) on delete set null
);

create table recurring_applied (
  recurring_id integer not null references recurring(id) on delete cascade,
  periode      text not null,
  applied_at   timestamptz not null default now(),
  primary key (recurring_id, periode)
);

-- View saldo dompet. Satu-satunya tempat saldo dihitung — tidak pernah
-- disimpan sebagai kolom (lihat CLAUDE.md). fixed_costs dan savings tidak
-- punya kolom tanggal asli (cuma month + year), jadi diproyeksikan ke
-- tanggal 20 periodenya (awal periode 20-19) untuk dibandingkan dengan
-- tanggal_awal dompet dan hari ini. Keenam sisi (income, variable, fixed,
-- saving, transfer masuk, transfer keluar) dibatasi <= hari ini (WIB)
-- supaya periode yang dibuka lebih awal untuk diisi tidak ikut menghitung
-- sebelum waktunya (lihat CHANGELOG / riwayat commit soal ini).
create or replace view wallet_balances as
select w.id, w.nama, w.jenis, w.saldo_awal, w.tanggal_awal, w.aktif, w.urutan, w.catatan,
  w.saldo_awal
    + coalesce(i.total, 0::bigint)
    - coalesce(v.total, 0::bigint)
    - coalesce(f.total, 0::bigint)
    - coalesce(sv.total, 0::bigint)
    + coalesce(tin.total, 0::bigint)
    - coalesce(tout.total, 0::bigint) as saldo
from wallets w
left join (
  select i2.wallet_id, sum(i2.amount)::bigint as total
  from incomes i2
  where i2.wallet_id is not null
    and i2.tanggal >= (select tanggal_awal from wallets where id = i2.wallet_id)
    and i2.tanggal <= (now() at time zone 'Asia/Jakarta')::date
  group by i2.wallet_id
) i on i.wallet_id = w.id
left join (
  select v2.wallet_id, sum(v2.amount)::bigint as total
  from variable_expenses v2
  where v2.wallet_id is not null
    and v2.tanggal >= (select tanggal_awal from wallets where id = v2.wallet_id)
    and v2.tanggal <= (now() at time zone 'Asia/Jakarta')::date
  group by v2.wallet_id
) v on v.wallet_id = w.id
left join (
  select fc.wallet_id, sum(fc.amount)::bigint as total
  from fixed_costs fc
  where fc.wallet_id is not null
    and make_date(
          fc.year,
          case fc.month
            when 'Januari' then 1 when 'Februari' then 2 when 'Maret' then 3
            when 'April' then 4 when 'Mei' then 5 when 'Juni' then 6
            when 'Juli' then 7 when 'Agustus' then 8 when 'September' then 9
            when 'Oktober' then 10 when 'November' then 11 when 'Desember' then 12
          end,
          20
        ) between (select tanggal_awal from wallets where id = fc.wallet_id)
              and (now() at time zone 'Asia/Jakarta')::date
  group by fc.wallet_id
) f on f.wallet_id = w.id
left join (
  select sv2.wallet_id, sum(sv2.amount)::bigint as total
  from savings sv2
  where sv2.wallet_id is not null
    and make_date(
          sv2.year,
          case sv2.month
            when 'Januari' then 1 when 'Februari' then 2 when 'Maret' then 3
            when 'April' then 4 when 'Mei' then 5 when 'Juni' then 6
            when 'Juli' then 7 when 'Agustus' then 8 when 'September' then 9
            when 'Oktober' then 10 when 'November' then 11 when 'Desember' then 12
          end,
          20
        ) between (select tanggal_awal from wallets where id = sv2.wallet_id)
              and (now() at time zone 'Asia/Jakarta')::date
  group by sv2.wallet_id
) sv on sv.wallet_id = w.id
left join (
  select t2.ke_id as wid, sum(t2.amount)::bigint as total
  from wallet_transfers t2
  where t2.tanggal >= (select tanggal_awal from wallets where id = t2.ke_id)
    and t2.tanggal <= (now() at time zone 'Asia/Jakarta')::date
  group by t2.ke_id
) tin on tin.wid = w.id
left join (
  select t3.dari_id as wid, sum(t3.amount)::bigint as total
  from wallet_transfers t3
  where t3.tanggal >= (select tanggal_awal from wallets where id = t3.dari_id)
    and t3.tanggal <= (now() at time zone 'Asia/Jakarta')::date
  group by t3.dari_id
) tout on tout.wid = w.id;

-- ============================================================
-- Modul Lamaran kerja
-- ============================================================

create table job_applications (
  id            uuid primary key default gen_random_uuid(),
  perusahaan    text not null,
  lokasi        text not null default '',
  jabatan       text not null,
  jenis         text not null default 'Tetap' check (jenis = any (array['MT','Magang','Tetap','Kontrak','Freelance'])),
  tempat        text not null default 'WFO' check (tempat = any (array['WFO','WFH','Hybrid'])),
  status        text not null default 'Applied' check (status = any (array['Progress','Applied','Screening','Interview','Offer','Rejected','Ghosted'])),
  tanggal_apply date not null default current_date,
  referensi     text not null default '',
  url           text not null default '',
  gaji          text not null default '',
  catatan       text not null default '',
  sumber        text not null default 'manual',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deadline      date,
  constraint perusahaan_terisi check (length(trim(perusahaan)) > 0),
  constraint jabatan_terisi check (length(trim(jabatan)) > 0)
);
create index job_applications_status_idx on job_applications (status);
create index job_applications_tanggal_idx on job_applications (tanggal_apply desc);
create index job_applications_deadline_idx on job_applications (deadline) where deadline is not null;
-- Duplikat perusahaan+jabatan (case/whitespace-insensitive) ditolak di
-- level database, bukan cuma dicek di kode — cariDuplikat() di lib/jobs.js
-- adalah pengecekan awal yang lebih ramah pesan error, index ini jaring
-- pengamannya.
create unique index job_applications_unik on job_applications (lower(trim(perusahaan)), lower(trim(jabatan)));
